# 收发数据转换器的编码
panda.http.pool.charset=UTF-8
# 连接池的最大连接数，0代表不限
panda.http.pool.max-total-connect=256
# 每个路由的最大连接数,如果只调用一个地址,可以将其设置为最大连接数
panda.http.pool.max-connect-per-route=256
# 客户端和服务器建立连接的超时时间(内部tcp在进行三次握手建立连接),ms
panda.http.pool.connect-timeout=30000
# 重试次数
panda.http.pool.retry-times=3
# 从连接池获取连接的timeout,不宜过大,ms
panda.http.pool.connection-request-timeout=200
# 长连接保持时间 单位ms,不宜过长
panda.http.pool.keep-alive-time-out=40000
# TCP 连接超时（毫秒）
panda.http.pool.socket-timeout=30000
# TCP连接最大空闲时间
panda.http.pool.idle-timeout=30000
# 禁用重定向的 RestTemplate 连接池设置5个连接数
panda.http.pool.disable-redirect-max-total-connect=5
# 是否要支持https
panda.https.support=true