########################Quartz\u96C6\u7FA4\u914D\u7F6E############################################
##############################quartzConfig_start#################################
spring.datasource.dynamic.datasource.qrtz.poll-name=qrtz
spring.datasource.dynamic.datasource.qrtz.url=jdbc:mysql://${panda.task.dataSource.host}:${panda.task.dataSource.port}/qrtz?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
spring.datasource.dynamic.datasource.qrtz.driver-class-name=${panda.task.dataSource.driver}
spring.datasource.dynamic.datasource.qrtz.username=${panda.task.dataSource.username}
spring.datasource.dynamic.datasource.qrtz.password=${panda.task.dataSource.password}
spring.datasource.dynamic.datasource.qrtz.type=${panda.task.dataSource.type}

spring.quartz.org.quartz.scheduler.instanceId = AUTO


spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=embedded
spring.quartz.properties.org.quartz.scheduler.instanceName=${panda.task.scheduler.instanceName}
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.dataSource=quartzDataSource
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.jobStore.isClustered=true
spring.quartz.properties.org.quartz.jobStore.clusterCheckinInterval=10000
spring.quartz.properties.org.quartz.jobStore.useProperties=false
spring.quartz.properties.org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
spring.quartz.properties.org.quartz.threadPool.threadCount=10
spring.quartz.properties.org.quartz.threadPool.threadPriority=5
spring.quartz.properties.org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true
##############################quartzConfig_end#################################